CREATE TABLE IF NOT EXISTS public.users(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar NOT NULL,
    surname varchar NOT NULL,
    username varchar NOT NULL,
    password varchar NOT NULL
)